name: TCAExample
options:
  bundleIdPrefix: com.tcaexample
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

packages:
  # Local Packages
  CounterFeature:
    path: CounterFeature

targets:
  # MARK: - TCAExample App
  TCAExample:
    type: application
    platform: iOS
    sources:
      - TCAExample/Sources
    resources:
      - path: TCAExample/Resources
        optional: true
    dependencies:
      - package: CounterFeature
        product: CounterFeature
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tcaexample.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: TCAExample
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait

schemes:
  TCAExample:
    build:
      targets:
        TCAExample: all
    run:
      config: Debug
      executable: TCAExample
    test:
      config: Debug
    profile:
      config: Release
      executable: TCAExample
    analyze:
      config: Debug
    archive:
      config: Release
